/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import model.Person;

/**
 *
 * @author EHY
 */
public class createJPanel1 extends javax.swing.JPanel {

    /**
     * Creates new form createJPanel
     */
    
    Person person;
    
    public createJPanel1(Person person) {
        initComponents();
        this.person = person;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblCAddress = new javax.swing.JLabel();
        lblCzip = new javax.swing.JLabel();
        lblCTele = new javax.swing.JLabel();
        lbCState = new javax.swing.JLabel();
        txtCAddress = new javax.swing.JTextField();
        txtCZip = new javax.swing.JTextField();
        txtCTele = new javax.swing.JTextField();
        txtCState = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        lblCountry = new javax.swing.JLabel();
        txtCCountry = new javax.swing.JTextField();

        lblTitle.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Create Home Address");

        lblCAddress.setText("Current Address");

        lblCzip.setText("Current Zip Code:");

        lblCTele.setText("Current Telephone number：");

        lbCState.setText("Current State：");

        txtCAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCAddressActionPerformed(evt);
            }
        });

        txtCZip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCZipActionPerformed(evt);
            }
        });

        txtCTele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCTeleActionPerformed(evt);
            }
        });

        txtCState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCStateActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblCountry.setText("Current Country:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblCzip)
                            .addComponent(lblCAddress)
                            .addComponent(lblCTele)
                            .addComponent(lbCState, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCountry, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(txtCZip, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(txtCTele, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(txtCState, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(btnSave)
                            .addComponent(txtCCountry))))
                .addContainerGap(212, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblTitle)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCAddress)
                    .addComponent(txtCAddress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCzip)
                    .addComponent(txtCZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCTele)
                    .addComponent(txtCTele, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbCState)
                    .addComponent(txtCState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCountry)
                    .addComponent(txtCCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(btnSave)
                .addGap(150, 150, 150))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCAddressActionPerformed

    private void txtCZipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCZipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCZipActionPerformed

    private void txtCTeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCTeleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCTeleActionPerformed

    private void txtCStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCStateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        person.setCaddress(txtCAddress.getText());
        person.setCzip(txtCZip.getText());
        person.setCstate(txtCState.getText());
        person.setCtele(txtCTele.getText());
        person.setCcountry(txtCCountry.getText());
        
        JOptionPane.showMessageDialog(this,"Home Address Information Saved.");
        
        
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel lbCState;
    private javax.swing.JLabel lblCAddress;
    private javax.swing.JLabel lblCTele;
    private javax.swing.JLabel lblCountry;
    private javax.swing.JLabel lblCzip;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtCAddress;
    private javax.swing.JTextField txtCCountry;
    private javax.swing.JTextField txtCState;
    private javax.swing.JTextField txtCTele;
    private javax.swing.JTextField txtCZip;
    // End of variables declaration//GEN-END:variables
}
